Support FIPS mode where possible
Computer systems can be configured to operate in compliance with the U.S.
Federal Information Processing Standards. Such configuration restricts usage of
MD5 due to its cryptographic insecurity. Trying to use `hashlib.md5()` on a FIPS
system raises an exception:

```
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
```

In Python 3.9 and newer, using MD5 for non-cryptographic purposes is allowed by
passing `usedforsecurity=False`.